// Real brand logos for the Tech Stack, sourced from Simple Icons (CC0 icon
// data; trademarks belong to their owners — used here nominatively to denote
// the tools in our stack). Each icon is a single 24×24 SVG path.
//
// Note: several major vendors (AWS, Azure, OpenAI, Salesforce, Adobe, Amazon,
// Microsoft, Klaviyo, Ahrefs, LinkedIn, Walmart, VS Code) have been removed from
// Simple Icons at the trademark owners' request, so those tools fall back to
// their monogram chip.
import {
  siClaude,
  siAda,
  siZapier,
  siMake,
  siN8n,
  siShopify,
  siBigcommerce,
  siWoocommerce,
  siGooglecloud,
  siVercel,
  siGithub,
  siBitbucket,
  siGoogleanalytics,
  siGoogletagmanager,
  siGoogleads,
  siMeta,
  siTiktok,
  siPinterest,
  siReddit,
  siHubspot,
  siMailchimp,
  siSemrush,
  siWordpress,
  siZendesk,
  siSap,
  siSage,
  siIntuit,
  siStripe,
  siAdyen,
  siPaypal,
  siLighthouse,
  siHotjar,
  siCloudflare,
  siPostman,
  siDocker,
  siJira,
  siFigma,
  siContentful,
  siPrismic,
  siDrupal,
  siSanity,
  siGooglebigquery,
  siAirtable,
  siConfluence,
} from "simple-icons";

// slug -> SVG path data (viewBox 0 0 24 24)
export const ICON_PATHS: Record<string, string> = {
  claude: siClaude.path,
  ada: siAda.path,
  zapier: siZapier.path,
  make: siMake.path,
  n8n: siN8n.path,
  shopify: siShopify.path,
  bigcommerce: siBigcommerce.path,
  woocommerce: siWoocommerce.path,
  googlecloud: siGooglecloud.path,
  vercel: siVercel.path,
  github: siGithub.path,
  bitbucket: siBitbucket.path,
  googleanalytics: siGoogleanalytics.path,
  googletagmanager: siGoogletagmanager.path,
  googleads: siGoogleads.path,
  meta: siMeta.path,
  tiktok: siTiktok.path,
  pinterest: siPinterest.path,
  reddit: siReddit.path,
  hubspot: siHubspot.path,
  mailchimp: siMailchimp.path,
  semrush: siSemrush.path,
  wordpress: siWordpress.path,
  zendesk: siZendesk.path,
  sap: siSap.path,
  sage: siSage.path,
  intuit: siIntuit.path,
  stripe: siStripe.path,
  adyen: siAdyen.path,
  paypal: siPaypal.path,
  lighthouse: siLighthouse.path,
  hotjar: siHotjar.path,
  cloudflare: siCloudflare.path,
  postman: siPostman.path,
  docker: siDocker.path,
  jira: siJira.path,
  figma: siFigma.path,
  contentful: siContentful.path,
  prismic: siPrismic.path,
  drupal: siDrupal.path,
  sanity: siSanity.path,
  googlebigquery: siGooglebigquery.path,
  airtable: siAirtable.path,
  confluence: siConfluence.path,
};

export function iconPath(slug?: string): string | undefined {
  return slug ? ICON_PATHS[slug] : undefined;
}
